### ISSUE TITLE
Is a use statement required

### ISSUE THREAD

**Issue by smartinsight-at** [peterujah/php-firebase-notification#1]
Thank you for potentially a very useful and well laid out class for firebase.

Do I require a Use statement. like "use Peterujah\NanoBlock\firebase", as I could not see one in the example.

I did not see this in the notes. is there a simple way to confirm that the class has loaded correctly.

Many Thanks

**Comment by peterujah** [comment]
> Thank you for potentially a very useful and well laid out class for firebase.
> 
> Do I require a Use statement. like "use Peterujah\NanoBlock\firebase", as I could not see one in the example.
> 
> I did not see this in the notes. is there a simple way to confirm that the class has loaded correctly.
> 
> Many Thanks



Yes, you can use it also like below. but first try Install/Download the latest update.

```php 
use \Peterujah\NanoBlock\FirebaseServiceModel;
use  \Peterujah\NanoBlock\FirebaseService;

$model = new FirebaseServiceModel();
$service = new FirebaseService(GOOGLE_FCM_API_KEY);
```

**Comment by smartinsight-at** [comment]
Thank you for that information. I will try again.

 

 

Regards


 

Adam Taylor 



 





SMART Insight Ltd 
Loyalty Card and Database Marketing Systems


p:  <tel:01275%20856683> 07765230957


w:  <http://smartinsight.co.uk/> smartinsight.co.uk


e: adam ***@***.***> @smartinsight.co.uk

z: https://us02web.zoom.us/j/6634582803


a: The Edge, Bucklands End, Nailsea, Bristol. BS48 4PN

 

	

 <http://smartinsight.co.uk/> Click to find out your company could benefit from an Intelligent Marketing System
